services:
  nginx:
    container_name: nginx
    image: ghcr.io/mirror-mwt/nginx-docker:main
    network_mode: host
    volumes:
      - /mnt/storage/mirror:/mirror:ro
    restart: "unless-stopped"
  rsyncd:
    container_name: rsyncd
    image: ghcr.io/mirror-mwt/rsyncd-docker:main
    network_mode: host
    volumes:
      - /mnt/storage/mirror:/mirror:ro
    restart: "unless-stopped"
  mirror-primary:
    container_name: mirror-primary
    image: ghcr.io/mirror-mwt/mirror-docker:main
    env_file: mirror-secret.env
    volumes:
      - /mnt/storage/mirror:/mirror
    restart: "unless-stopped"
  makerepo-rclone:
    container_name: makerepo-rclone
    image: ghcr.io/mirror-mwt/makerepo-docker:main
    environment:
      - MWT_GITHUB_URL=https://api.github.com/repos/rclone/rclone/releases
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=Rclone
      - REPREPRO_ARCHITECTURES=amd64 i386 arm64 armhf armel mips mipsel
      - REPREPRO_SIGNWITH=B7BE5AC2
      - CRON_TIME=16 3-23/6 * * *
    env_file:
      - makerepo-secret.env
    volumes:
      - /mnt/storage/mirror/rclone:/dist
      - reprepro-db-rclone:/root/reprepro/db
    restart: "unless-stopped"
  makerepo-zoom:
    container_name: makerepo-zoom
    image: ghcr.io/mirror-mwt/makerepo-docker:main
    environment:
      - MWT_DIRECT_DOWNLOADS=https://zoom.us/client/latest/zoom_amd64.deb https://zoom.us/client/latest/zoom_x86_64.rpm
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=Zoom
      - REPREPRO_ARCHITECTURES=amd64
      - REPREPRO_SIGNWITH=B7BE5AC2
      - CRON_TIME=46 3-23/6 * * *
    env_file:
      - makerepo-secret.env
    volumes:
      - /mnt/storage/mirror/zoom:/dist
      - reprepro-db-zoom:/root/reprepro/db
    restart: "unless-stopped"
  makerepo-rstudio-main:
    container_name: makerepo-rstudio-main
    image: ghcr.io/mirror-mwt/makerepo-docker:main
    environment:
      - MWT_DIRECT_DOWNLOADS=https://rstudio.org/download/latest/stable/desktop/jammy/rstudio-latest-amd64.deb~jammy https://rstudio.org/download/latest/stable/server/jammy/rstudio-server-latest-amd64.deb~jammy https://rstudio.org/download/latest/stable/desktop/rhel9/rstudio-latest-x86_64.rpm~el9 https://rstudio.org/download/latest/stable/server/rhel9/rstudio-server-rhel-latest-x86_64.rpm~el9 https://rstudio.org/download/latest/stable/desktop/rhel8/rstudio-latest-x86_64.rpm~el8 https://rstudio.org/download/latest/stable/server/rhel8/rstudio-server-rhel-latest-x86_64.rpm~el8
      - REPREPRO_ORIGIN=mirror.mwt.me
      - REPREPRO_LABEL=RStudio
      - REPREPRO_CODENAMES=jammy
      - REPREPRO_ARCHITECTURES=amd64
      - REPREPRO_SIGNWITH=B7BE5AC2
      - CRON_TIME=03 5-23/6 * * *
    env_file:
      - makerepo-secret.env
    volumes:
      - /mnt/storage/mirror/rstudio/deb/jammy:/dist/deb
      - /mnt/storage/mirror/rstudio/rpm:/dist/rpm
      - reprepro-db-rstudio-jammy:/root/reprepro/db
    restart: "unless-stopped"
  makerepo-rstudio-focal:
    container_name: makerepo-rstudio-focal
    image: ghcr.io/mirror-mwt/makerepo-docker:main
    environment:
      - MWT_DIRECT_DOWNLOADS=https://rstudio.org/download/latest/stable/desktop/focal/rstudio-latest-amd64.deb~focal https://rstudio.org/download/latest/stable/server/focal/rstudio-server-latest-amd64.deb~focal
      - REPREPRO_LABEL=RStudio
      - REPREPRO_CODENAMES=focal
      - REPREPRO_ARCHITECTURES=amd64
      - REPREPRO_SIGNWITH=B7BE5AC2
      - CRON_TIME=51 5-23/6 * * *
    env_file:
      - makerepo-secret.env
    volumes:
      - /mnt/storage/mirror/rstudio/deb/focal:/dist/deb
      - reprepro-db-rstudio-focal:/root/reprepro/db
    restart: "unless-stopped"
volumes:
  reprepro-db-rclone:
  reprepro-db-zoom:
  reprepro-db-rstudio-jammy:
  reprepro-db-rstudio-focal:
